spring.application.name=todoverwaltung

# Aufsetzen der H2 Datenbank 
spring.datasource.url=jdbc:h2:file:./data/todoverwaltung
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tabellen werden beim Starten aus den entsprechenden Entities erzeugt 
spring.jpa.hibernate.ddl-auto=update

# Die Weboberfläche der Datenbank ist erreichbar unter http://localhost:8080/h2-console/
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging der SQL-Statements 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
